version: "3"
services:

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Super
      MYSQL_DATABASE: pruebaspringboot
      MYSQL_USER: root
      MYSQL_PASSWORD: Mariposa$$100
    volumes:
      - ./initSQL:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  adminer:
    image: adminer
    ports:
      - 8888:8080